// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyXemA3TtOyDyPKRlGhP8yK0xa9DAKIys',
    appId: '1:438616619810:web:8772ad66c20e9f7e8d837b',
    messagingSenderId: '438616619810',
    projectId: 'cities-fe5d4',
    authDomain: 'cities-fe5d4.firebaseapp.com',
    storageBucket: 'cities-fe5d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7xzC4y9qjExAgHpWc7fovw5mTqbQ7Akc',
    appId: '1:438616619810:android:cf26b1613489dcf08d837b',
    messagingSenderId: '438616619810',
    projectId: 'cities-fe5d4',
    storageBucket: 'cities-fe5d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ZkQEg_1yFWW8JsJkXb2FE4h9fyq0E8k',
    appId: '1:438616619810:ios:fbc26d9a01cbe4248d837b',
    messagingSenderId: '438616619810',
    projectId: 'cities-fe5d4',
    storageBucket: 'cities-fe5d4.firebasestorage.app',
    iosBundleId: 'com.example.fassign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ZkQEg_1yFWW8JsJkXb2FE4h9fyq0E8k',
    appId: '1:438616619810:ios:fbc26d9a01cbe4248d837b',
    messagingSenderId: '438616619810',
    projectId: 'cities-fe5d4',
    storageBucket: 'cities-fe5d4.firebasestorage.app',
    iosBundleId: 'com.example.fassign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyXemA3TtOyDyPKRlGhP8yK0xa9DAKIys',
    appId: '1:438616619810:web:faffd28fc7f302798d837b',
    messagingSenderId: '438616619810',
    projectId: 'cities-fe5d4',
    authDomain: 'cities-fe5d4.firebaseapp.com',
    storageBucket: 'cities-fe5d4.firebasestorage.app',
  );
}
